apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows default service account to edit pods
kind: ClusterRoleBinding
metadata:
  name: default-edit
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io